server:
  port: 8082

spring:
  profiles:
    active: prod
  application:
    name: zyz-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: zyz-user
          uri: lb://zyz-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: zyz-auth
          uri: lb://zyz-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
