#监听端口
server:
  port: 8101
spring:
  profiles:
    active: prod
  application:
    name: zyz-user
  cloud:
    consul:
      host: localhost
      port: 40001
      discovery:
        heartbeat:
          enabled: true
        health-check-path: /health
        health-check-interval: 10
      config:
        enabled: false