#监听端口
server:
  port: 8100
spring:
  profiles:
    active: dev
  application:
    name: zyz-auth
  cloud:
    consul:
      host: 192.168.5.247
      port: 40001
      discovery:
        heartbeat:
          enabled: true
        health-check-path: /health
        health-check-interval: 10
      config:
        enabled: false